language: node_js
node_js:
  - "11.3"
install:
  - yarn install
script:
  - yarn run build-prod
cache:
  directories:
    - node_modules # NPM packages
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      repo: pongee/plantuml-editor
    local_dir: docs